### ISSUE TITLE
Where do we sanitise the incoming markup? (Hooks implementation)

### ISSUE THREAD

**Issue by tanmayaBiswalOdiware** [sibiraj-s/marked-react#12] opened 2023-04-19 08:08 UTC
Writing DOM.purify inside renderer, right before returning the parsed markup leads to problems like showing [object Object] for things like bold and italics.

```js
    const renderer = {
        paragraph(text) {
            console.log("text =", text)
            // let cleanHTML = DOMPurify.sanitize(text, { USE_PROFILES: { html: true } });
            return <MathJax key={uniqueId()}>{text}</MathJax>
            // return <span>hahah lol</span>
        },
        html(text) {
            let cleanHTML = DOMPurify.sanitize(text, { USE_PROFILES: { html: true } });
            return <span key={"title-span"} dangerouslySetInnerHTML={{ __html: cleanHTML }}></span>;
        }
    }
```

Where do you suggest we purify the input?

**Comment by sibiraj-s** [comment] 2023-04-19 11:52
I have never been in a situation to sanitize markdown files.  But If you ask me, I would heavily recommend to sanitize the content before storing in DB, processing it in client side is not recommended, as it can be bypassed on way or other.

And to your question. your code looks fine, and should work fine. Can you please verify the output of the sanitize function once (though it shouldn't be an issue). 

And please provide a reproducible example in stackblitz/codesandbox maybe. Thanks

**Comment by tanmayaBiswalOdiware** [comment] 2023-04-20 05:18
Well, there is sanitization happening on the server side as well. But the best practice is usually to sanitize them on both ends (I can just no implement it and tell my overlords that it been done though😂 but I digress).

Anyway, as far as the code shown above goes - it works fine for the HTML, but it doesn't work for some other type of input like bold, italics and so on. I am going to post a sandbox soon. Let me see if it can be reproduced.

Thanks for the prompt reply and hard work!

**Comment by sibiraj-s** [comment] 2023-04-20 05:29
Ah, I get it now. I'll see why you are referring to now. I didn't understand fully earlier.

You must return a valid react node. See [here](https://github.com/sibiraj-s/marked-react/blob/6fbd187307fea86d0b65de58d4510627e4534bba/src/Markdown.ts#L54) . I'll also look into this once.

**Comment by tanmayaBiswalOdiware** [comment] 2023-04-20 05:37
Yea, that's the problem. Sanitizing the argument passed into `renderer` messes up the React Node, and hence a weird output is received. That was my diagnosis. For now, I am essentially running the sanitization in `useEffect` where I am getting my data from API call.

**Comment by sibiraj-s** [comment] 2023-04-20 05:41
I have just tried it and it works fine as expect 🤔 . Make sure the implementation is for the renderer.

This is the code i used

```js
strong(text){
  const clean = DOMPurify.sanitize(text as string)
  return <CustomComponent>{clean}</CustomComponent>
}
```

You can refer to some examples [here](https://github.com/sibiraj-s/marked-react/blob/master/stories/1-CustomRenderer.stories.tsx) from storybook stories

**Comment by tanmayaBiswalOdiware** [comment] 2023-04-20 07:26
Ok, I have got the [Sandbox](https://codesandbox.io/p/github/codesandbox/codesandbox-template-vite-react/csb-h6xx4x/DOMPurify-with-marked-react). Maybe I am doing something wrong.

**Comment by sibiraj-s** [comment] 2023-04-20 07:45
I think I see whats happening whats happening. So the elements like bold, italics are parsed first and converted to react element before passing to paragraph.

This react elements are just objects, which when passed to purifier, is converted to object object.

I tried differently before, hence I couldn't see this.

**Comment by sibiraj-s** [comment] 2023-04-26 05:56
![Screenshot 2023-04-26 at 11 25 59 AM](https://user-images.githubusercontent.com/20282546/234482290-6de33a4b-a20e-4aad-a4dc-3f44d65b31cb.png)

marked doesn't sanitize. Ref: https://marked.js.org/#usage

**Comment by tanmayaBiswalOdiware** [comment] 2023-04-26 07:00
Yea, marked doesn't sanitize. But it has a way to handle sanitization at some point in the rendering cycle.
Ref: https://marked.js.org/using_pro#hooks
See the second example of them using postprocess hook.

**Comment by sibiraj-s** [comment] 2023-04-26 08:28
Oh didn't know that. Thanks.

Yeah it is simple in their case as it is just a simple string of html. Where are the parser here converts to React components. I don't see an option here, even a window to do something.

**Comment by sibiraj-s** [comment] 2023-04-26 08:32
I did not originally plan to add option to implement sanitization or provide some hooks to pre/post process stuffs, but I am open to suggestions for the implementation.

**Comment by sibiraj-s** [comment] 2023-04-26 08:35
Why not just pass the content through dom-purify first then send it to marked-react. I believe dom-purify won't remove anything that is related to markdown formatting. 🤔 

did you try that and created any problems?

**Comment by sibiraj-s** [comment] 2023-04-26 08:38
![Screenshot 2023-04-26 at 2 07 31 PM](https://user-images.githubusercontent.com/20282546/234519123-5d2080e9-d16e-400e-890b-b16d434ce01f.png)

**Comment by tanmayaBiswalOdiware** [comment] 2023-04-26 08:41
That is in fact what I am doing right now. It looks fine with the content I have tested. 

It's just that the processing takes place in two separate places, you know. Once I am sanitizing else where, and then later on in the `return` I push the data in the Marked.

It works, but the happen separately. So yes, I was just nitpicking but it would have been sweet if all of those could happen altogether. If you get what I mean. 

That is why I wrote, it's not urgent, but it definitely will make the package better overall.

**Comment by sibiraj-s** [comment] 2023-04-26 08:43
Cool. In that case, I'll leave this open for sometime, may be some idea might popup overtime or someone could suggest a better solution to make this seamless.

**Comment by tanmayaBiswalOdiware** [comment] 2023-04-26 08:45
Sure, that would be good. I do not have a lot of experience with developing packages but I will try to think of something if we can somehow implement hooks (and even tokenizer but I just don't understand tokenizer myself haha)

**Comment by sibiraj-s** [comment] 2024-12-08 04:44
Closing this, since its been open for a while, the go to option for now is to sanitize the input first and then pass it on to the library.

**Closed by sibiraj-s** 2024-12-08 04:44 UTC
