### ISSUE TITLE
Punctuation Invalid RegExp: Invalid Escape

### ISSUE THREAD

**Issue by ARIPRASATH4664** [sibiraj-s/marked-react#27] opened 2024-05-24 08:14 UTC
Issue when upgrading the package seems to be with marked library which is an internal part.

![image](https://github.com/sibiraj-s/marked-react/assets/65212662/eb2af060-a464-4b39-85c6-56e1d7ad3b05)

**Comment by sibiraj-s** [comment] 2024-12-04 13:42
Sorry for the delayed reply, Since the issue is not with this repo. closing it. And hope this is resolved by this time.

**Closed by sibiraj-s** 2024-12-04 13:42 UTC
